In [1]:
import plotly.graph_objects as go
import numpy as np

In [31]:
'''
takes SMA, e, b as params, varies E
'''
a = 1.55e+8    #km
e = 0.975
b = a*np.sqrt(1- e**2)


In [32]:
a*(1+e)

306125000.0

In [33]:
E_list = np.linspace(0, 2*np.pi, 1000)

r_e_list = []
r_p_list = []

for E in E_list:
    
    r_e = a*(np.cos(E) - e)
    r_p = b*np.sin(E)
    
    r_e_list.append(r_e)
    r_p_list.append(r_p)
    

In [7]:
a2 = 27536     #km
e2 = 0.582
b2 = a2*np.sqrt(1- e2**2)

In [8]:
E_list = np.linspace(0, 2*np.pi, 1000)

r_e_list2 = []
r_p_list2 = []

for E in E_list:
    
    r_e = a2*(np.cos(E) - e2)
    r_p = b2*np.sin(E)
    
    r_e_list2.append(r_e)
    r_p_list2.append(r_p)

In [14]:
a3 = 2*6378     #km
e3 = 0
b3 = a3*np.sqrt(1- e3**2)

In [15]:
E_list = np.linspace(0, 2*np.pi, 1000)

r_e_list3 = []
r_p_list3 = []

for E in E_list:
    
    r_e = a3*(np.cos(E) - e3)
    r_p = b3*np.sin(E)
    
    r_e_list3.append(r_e)
    r_p_list3.append(r_p)

In [9]:
x = r_e_list2[0]
y = r_p_list2[0]

angle = 73*np.pi/180

In [64]:
x*np.cos(angle) + y*np.sin(angle)

4662.05330647731

In [66]:
1*np.cos(angle) + 0*np.sin(angle)

0.29237170472273677

In [61]:
r_e_list2[0], a2*(1-e2)

(15945.637799999999, 15945.637799999999)

In [59]:
r_p_list2[0]

0.0

In [46]:
#given E0
E0 = 156.598*np.pi/180

In [47]:
np.argwhere(abs(E_list-E0) <= 0.01)

array([[433],
       [434],
       [435],
       [436]], dtype=int64)

In [48]:
E_list[435]

2.735921530153273

In [49]:
r_e_list[435], r_p_list[435] 

(-59333.25372312846, 8857.185372385498)

In [50]:
E = 0

print(a*(np.cos(E) - e))
print(b*np.sin(E))

8100.461500000001
0.0


In [51]:
#rotate line of nodes
deltaw = 73*np.pi/180

In [76]:
r_e_list2_shift = []
r_p_list2_shift = []

for i in range(len(r_e_list2)):
    x = r_e_list2[i]
    y = r_p_list2[i]

    angle = -73*np.pi/180
    
    r_e_list2_shift.append(x*np.cos(angle) + y*np.sin(angle))
    r_p_list2_shift.append(-x*np.sin(angle) + y*np.cos(angle))

In [77]:
r_e_list2_shift[0]

4662.05330647731

In [78]:
r_p_list2_shift[0]

15248.889265003952

In [35]:
fig = go.Figure()

fig.add_trace(go.Scatter(x=r_e_list, y=r_p_list,
                    mode='lines',
                    name='orbit1'))
'''
fig.add_trace(go.Scatter(x=r_e_list2, y=r_p_list2,
                    mode='lines',
                    name='orbit2'))'''
'''
fig.add_trace(
    go.Scatter(
        mode='markers',
        x=[15248.889265003952],
        y=[4662.05330647731],
        marker=dict(
            color='red',
            size=10,
            line=dict(
                color='red',
                width=1
            )
        ),
        showlegend=False
    )
)'''


fig.update_layout(
    title="Orbit about Sun - HW9",
    xaxis_title="E (km)",
    yaxis_title="P (km)",
    font=dict(
        family="Arial",
        size=18,
        color="#000000"
    )
)

fig.update_layout(
    yaxis = dict(
      scaleanchor = "x",
      scaleratio = 1,
    ),
    xaxis = dict(
      scaleanchor = "x",
      scaleratio = 1,
    ),
    shapes=[
        # filled circle
        dict(
            type="circle",
            xref="x",
            yref="y",
            fillcolor="orange",
            x0=-696340,
            y0=-696340,
            x1=696340,
            y1=696340,
            line_color="red",
        ),
    ]
)
fig.show()

In [16]:
fig = go.Figure()

fig.add_trace(go.Scatter(x=r_e_list, y=r_p_list,
                    mode='lines',
                    name='orbit - before'))

fig.add_trace(go.Scatter(x=r_e_list2, y=r_p_list2,
                    mode='lines',
                    name='transfer'))

fig.add_trace(go.Scatter(x=r_e_list3, y=r_p_list3,
                    mode='lines',
                    name='orbit - after'))

'''fig.add_trace(
    go.Scatter(
        mode='markers',
        x=[15248.889265003952],
        y=[4662.05330647731],
        marker=dict(
            color='red',
            size=10,
            line=dict(
                color='red',
                width=1
            )
        ),
        showlegend=False
    )
)'''


fig.update_layout(
    title="Orbit about Earth - HW7 #1d",
    xaxis_title="X (km)",
    yaxis_title="Y (km)",
    font=dict(
        family="Arial",
        size=18,
        color="#000000"
    )
)

fig.update_layout(
    yaxis = dict(
      scaleanchor = "x",
      scaleratio = 1,
    ),
    xaxis = dict(
      scaleanchor = "x",
      scaleratio = 1,
    ),
    shapes=[
        # filled circle
        dict(
            type="circle",
            xref="x",
            yref="y",
            fillcolor="PaleTurquoise",
            x0=-6378,
            y0=-6378,
            x1=6378,
            y1=6378,
            line_color="LightSeaGreen",
        ),
    ]
)

fig.show()

In [12]:

    
fig = go.Figure()

fig.add_trace(go.Scatter(x=r_e_list, y=r_p_list,
                    mode='lines',
                    name='orbit'))

fig.add_trace(
    go.Scatter(
        mode='markers',
        x=[10962.54014226883],
        y=[-2903.495614724],
        marker=dict(
            color='red',
            size=10,
            line=dict(
                color='red',
                width=1
            )
        ),
        showlegend=False
    )
)


fig.update_layout(
    title="Orbit about Earth - HW5 #3bii",
    xaxis_title="X (km)",
    yaxis_title="Y (km)",
    font=dict(
        family="Arial",
        size=18,
        color="#000000"
    )
)

fig.update_layout(
    autosize=True,
    width=700,
    height=700,
    shapes=[
        # filled circle
        dict(
            type="circle",
            xref="x",
            yref="y",
            fillcolor="PaleTurquoise",
            x0=-6378,
            y0=-6378,
            x1=6378,
            y1=6378,
            line_color="LightSeaGreen",
        ),
    ]
)

fig.show()

In [39]:
a = 1986.18    #km
b = 8766.784
e = 4.533
p = 38826.02

In [79]:
theta_list = np.linspace(-np.pi/2, np.pi/2, 2000)

r_e_list = []
r_p_list = []

for theta in theta_list:
    
    r = abs(p/(1+(e*np.cos(theta))))
    
    r_e = r*np.cos(theta)
    r_p = r*np.sin(theta)
    
    r_e_list.append(r_e)
    r_p_list.append(r_p)
    

In [80]:
#given E0
theta0 = -0.301

In [93]:
theta1 = -0.2228

In [94]:
np.argwhere(abs(theta_list-theta1) <= 0.01)

array([[852],
       [853],
       [854],
       [855],
       [856],
       [857],
       [858],
       [859],
       [860],
       [861],
       [862],
       [863],
       [864]], dtype=int64)

In [99]:
theta_list[855]

-0.22709361602987754

In [100]:
r_e_list[855], r_p_list[855] 

(6983.911436846828, -1613.8402824124203)

In [101]:
fig = go.Figure()

fig.add_trace(go.Scatter(x=r_e_list, y=r_p_list,
                    mode='lines',
                    name='orbit'))

fig.update_layout(
    title="Orbit about Mars - HW4 #3c",
    xaxis_title="X (km)",
    yaxis_title="Y (km)",
    font=dict(
        family="Arial",
        size=18,
        color="#000000"
    )
)

fig.update_layout(
    yaxis = dict(
      scaleanchor = "x",
      scaleratio = 1,
    ),
    xaxis = dict(
      scaleanchor = "x",
      scaleratio = 1,
    ),
    shapes=[
        # filled circle
        dict(
            type="circle",
            xref="x",
            yref="y",
            fillcolor="orange",
            x0=-3396,
            y0=-3396,
            x1=3396,
            y1=3396,
            line_color="darkred",
        ),
    ]
)

fig.add_trace(
    go.Scatter(
        mode='markers',
        x=[6983.911436846828],
        y=[-1613.8402824124203],
        marker=dict(
            color='red',
            size=10,
            line=dict(
                color='red',
                width=1
            )
        ),
        showlegend=False
    )
)

fig.show()

In [61]:

    
fig = go.Figure()

fig.add_trace(go.Scatter(x=r_e_list, y=r_p_list,
                    mode='lines',
                    name='orbit'))
#(-11137.083963748784, 3447.2050264734216)
fig.add_trace(
    go.Scatter(
        mode='markers',
        x=[-11137.083963748784],
        y=[3447.2050264734216],
        marker=dict(
            color='red',
            size=10,
            line=dict(
                color='red',
                width=1
            )
        ),
        showlegend=False
    )
)

fig.update_layout(
    title="Orbit about Earth - HW4 #2c",
    xaxis_title="X (km)",
    yaxis_title="Y (km)",
    font=dict(
        family="Arial",
        size=18,
        color="#000000"
    )
)

fig.update_layout(
    autosize=False,
    width=700,
    height=700,
    shapes=[
        # filled circle
        dict(
            type="circle",
            xref="x",
            yref="y",
            fillcolor="darkorange",
            x0=-6378,
            y0=-6378,
            x1=6378,
            y1=6378,
            line_color="darkred",
        ),
    ]
)

fig.show()

In [2]:
omega = 45*np.pi/180
theta = 260*np.pi/180
inclin = 35*np.pi/180

In [3]:
DCM = np.array([
    [np.cos(omega)*np.cos(theta) - np.sin(omega)*np.cos(inclin)*np.sin(theta),
    -np.cos(omega)*np.sin(theta) - np.sin(omega)*np.cos(inclin)*np.cos(theta),
    np.sin(omega)*np.sin(inclin)],
    [np.sin(omega)*np.cos(theta) + np.cos(omega)*np.cos(inclin)*np.sin(theta),
    -np.sin(omega)*np.sin(theta) + np.cos(omega)*np.cos(inclin)*np.cos(theta),
    -np.cos(omega)*np.sin(inclin)],
    [np.sin(inclin)*np.sin(theta), np.sin(inclin)*np.cos(theta), np.cos(inclin)]
])

In [28]:
DCM@np.array([[2.07],[3.885],[0]])

array([[ 3.93452813],
       [-0.64010534],
       [-1.86758629]])

In [4]:
DCM@np.array([[5.3*6378],[0],[0]])

array([[ 15131.76705991],
       [-23433.05756528],
       [-19094.27375804]])

In [30]:
DCM

array([[ 0.1767767 ,  0.91855865,  0.35355339],
       [-0.88388348,  0.30618622, -0.35355339],
       [-0.4330127 , -0.25      ,  0.8660254 ]])